services:
  - type: web
    name: komunalka
    region: frankfurt
    runtime: python
    buildCommand: "./build.sh"
    startCommand: gunicorn komunalka.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "komunalka-9jok.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: komunalka.settings
      - key: DATABASE_URL
        fromDatabase:
          name: komunalka-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "True"
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true

databases:
  - name: komunalka-db
    plan: free
    region: frankfurt

postdeploy:
  command: >
    python manage.py migrate &&
    echo "
from django.contrib.auth import get_user_model;
User = get_user_model();
username = 'admin';
email = 'admin@example.com';
password = 'admin123';
User.objects.filter(username=username).exists() or User.objects.create_superuser(username, email, password)
" | python manage.py shell
