# Generated by Django 5.2 on 2025-05-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ('id',), 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='Apartments',
        ),
    ]
