# Generated by Django 5.2 on 2025-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0002_alter_apartment_options_alter_apartment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Централизованное отопление.'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='heating',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за отопление'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='intercom',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за интерком'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='tariff_garbage',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на вывоз мусора'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='tariff_heating',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на отопление'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='tariff_lift',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на лифт'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='tariff_payment',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на квартплату'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_apart_payment',
            field=models.BooleanField(default=False, verbose_name='Наличие квартплаты.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_electricity',
            field=models.PositiveIntegerField(null=True, verbose_name='Электричество.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_garbage',
            field=models.BooleanField(default=False, verbose_name='Вывоз мусора.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_gas',
            field=models.PositiveIntegerField(null=True, verbose_name='Наличие газа и счётчика.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='Наличие интернета.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_water',
            field=models.PositiveIntegerField(null=True, verbose_name='Наличие доставки воды и счётчика.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_registered',
            field=models.PositiveIntegerField(verbose_name='Количество зарегистрированных в квартире'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='uses_lift',
            field=models.BooleanField(default=False, verbose_name='Наличие лифта.'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_meter_one',
            field=models.PositiveIntegerField(null=True, verbose_name='Показания электр.счётчика-1'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_meter_two',
            field=models.PositiveIntegerField(null=True, verbose_name='Показания электр.счётчика - 2'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_tariff_one',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на электроэнергию-1'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_tariff_two',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на электроэнергию - 2'),
        ),
        migrations.AlterField(
            model_name='gasindicators',
            name='gas_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='цена за доставку газа'),
        ),
        migrations.AlterField(
            model_name='gasindicators',
            name='gas_meter',
            field=models.PositiveIntegerField(null=True, verbose_name='Показания газ.счётчика'),
        ),
        migrations.AlterField(
            model_name='gasindicators',
            name='gas_tariff_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на газ по счётчику'),
        ),
        migrations.AlterField(
            model_name='gasindicators',
            name='gas_tariff_no_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на газ без счётчика'),
        ),
        migrations.AlterField(
            model_name='otherpayments',
            name='apart_payment',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за квартиру'),
        ),
        migrations.AlterField(
            model_name='otherpayments',
            name='garbage',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за мусор'),
        ),
        migrations.AlterField(
            model_name='otherpayments',
            name='internet',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за интернет'),
        ),
        migrations.AlterField(
            model_name='otherpayments',
            name='lift',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за лифт'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_abon_plata',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='aбонплата на воду'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_meter_one',
            field=models.PositiveIntegerField(null=True, verbose_name='Показания вод.счётчика #1'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_meter_two',
            field=models.PositiveIntegerField(null=True, verbose_name='Показания вод.счётчика #2'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_tariff_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду по счётчику'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_tariff_nocounter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду без счётчика'),
        ),
    ]
