# Generated by Django 5.2 on 2025-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0003_apartment_has_heating_apartment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_intercom',
            field=models.BooleanField(default=False, verbose_name='Домофон.'),
        ),
        migrations.AlterField(
            model_name='otherpayments',
            name='intercom',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за домофон'),
        ),
    ]
