# Generated by Django 5.2 on 2025-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0005_apartment_area_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area_apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_registered',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество зарегистрированных в квартире'),
        ),
    ]
