# Generated by Django 5.2 on 2025-05-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0006_alter_apartment_area_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='gas_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Доставка газа'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_apart_payment',
            field=models.BooleanField(default=False, verbose_name='Квартплата.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_gas',
            field=models.PositiveIntegerField(null=True, verbose_name='Газ.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Центральное отопление.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='Интернет.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_water',
            field=models.PositiveIntegerField(null=True, verbose_name='Вода.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='uses_lift',
            field=models.BooleanField(default=False, verbose_name='Лифт.'),
        ),
    ]
