# Generated by Django 5.2 on 2025-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0007_apartment_gas_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='gas_delivery',
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_gas_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка газа.'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='gas_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Доставка газа'),
        ),
    ]
