# Generated by Django 5.2 on 2025-05-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0008_remove_apartment_gas_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasindicators',
            name='apartament',
        ),
        migrations.RemoveField(
            model_name='otherpayments',
            name='apartament',
        ),
        migrations.RemoveField(
            model_name='waterindicators',
            name='apartament',
        ),
        migrations.DeleteModel(
            name='ElectricityIndicators',
        ),
        migrations.DeleteModel(
            name='GasIndicators',
        ),
        migrations.DeleteModel(
            name='OtherPayments',
        ),
        migrations.DeleteModel(
            name='WaterIndicators',
        ),
    ]
