# Generated by Django 5.2 on 2025-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0009_remove_gasindicators_apartament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_hot_water',
            field=models.PositiveIntegerField(null=True, verbose_name='Горячая вода.'),
        ),
    ]
