# Generated by Django 5.2 on 2025-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0010_apartment_has_hot_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_water_abon_plata',
            field=models.BooleanField(default=False, verbose_name='Абонплата за воду.'),
        ),
    ]
