# Generated by Django 5.2 on 2025-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0011_apartment_has_water_abon_plata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='has_apart_payment',
            field=models.BooleanField(default=False, verbose_name='Квартплата'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_electricity',
            field=models.PositiveIntegerField(null=True, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_garbage',
            field=models.BooleanField(default=False, verbose_name='Вывоз мусора'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_gas',
            field=models.PositiveIntegerField(null=True, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_gas_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка газа'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Центральное отопление'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_hot_water',
            field=models.PositiveIntegerField(null=True, verbose_name='Горячая вода'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_intercom',
            field=models.BooleanField(default=False, verbose_name='Домофон'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_water_abon_plata',
            field=models.BooleanField(default=False, verbose_name='Абонплата за воду'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='uses_lift',
            field=models.BooleanField(default=False, verbose_name='Лифт'),
        ),
    ]
