# Generated by Django 5.2 on 2025-05-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartaments', '0009_remove_gasindicators_apartament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('electro_meter_one', models.PositiveIntegerField(null=True, verbose_name='Показания электр.счётчика-1')),
                ('electro_tariff_one', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на электроэнергию-1')),
                ('electro_meter_two', models.PositiveIntegerField(null=True, verbose_name='Показания электр.счётчика - 2')),
                ('electro_tariff_two', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на электроэнергию - 2')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartaments.apartment', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Электроэнергия',
                'verbose_name_plural': 'Электроэнергия',
                'db_table': 'Еlectricity',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GasIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('gas_meter', models.PositiveIntegerField(null=True, verbose_name='Показания газ.счётчика')),
                ('gas_tariff_counter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на газ по счётчику')),
                ('gas_tariff_no_counter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на газ без счётчика')),
                ('gas_delivery', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Доставка газа')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartaments.apartment', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Газ',
                'verbose_name_plural': 'Газ',
                'db_table': 'Gas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OtherPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('apart_payment', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за квартиру')),
                ('tariff_payment', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на квартплату')),
                ('garbage', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за мусор')),
                ('tariff_garbage', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на вывоз мусора')),
                ('lift', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за лифт')),
                ('tariff_lift', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на лифт')),
                ('heating', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за отопление')),
                ('tariff_heating', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на отопление')),
                ('internet', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за интернет')),
                ('intercom', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='платеж за домофон')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartaments.apartment', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Другие платежи',
                'verbose_name_plural': 'Другие платежи',
                'db_table': 'OtherPayments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WaterIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('water_meter_one', models.PositiveIntegerField(null=True, verbose_name='Показания вод.счётчика #1')),
                ('water_meter_two', models.PositiveIntegerField(null=True, verbose_name='Показания вод.счётчика #2')),
                ('water_tariff_counter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду по счётчику')),
                ('water_tariff_nocounter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду без счётчика')),
                ('water_abon_plata', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='aбонплата на воду')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartaments.apartment', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вода',
                'verbose_name_plural': 'Вода',
                'db_table': 'Water',
                'ordering': ('id',),
            },
        ),
    ]
