# Generated by Django 5.2 on 2025-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_gasindicators_gas_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpayments',
            name='gas_delivery',
        ),
        migrations.AddField(
            model_name='gasindicators',
            name='gas_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Доставка газа'),
        ),
    ]
