# Generated by Django 5.2 on 2025-05-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_otherpayments_gas_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherpayments',
            old_name='tariff_payment',
            new_name='tariff_apart_payment',
        ),
        migrations.RemoveField(
            model_name='otherpayments',
            name='apart_payment',
        ),
        migrations.RemoveField(
            model_name='otherpayments',
            name='garbage',
        ),
        migrations.RemoveField(
            model_name='otherpayments',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='otherpayments',
            name='lift',
        ),
    ]
