# Generated by Django 5.2 on 2025-05-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_tariff_payment_otherpayments_tariff_apart_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricityindicators',
            old_name='apartament',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='gasindicators',
            old_name='apartament',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='otherpayments',
            old_name='apartament',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='waterindicators',
            old_name='apartament',
            new_name='apartment',
        ),
    ]
