# Generated by Django 5.2 on 2025-05-31 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartaments', '0010_apartment_has_hot_water'),
        ('services', '0005_rename_apartament_electricityindicators_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasindicators',
            name='number_registered_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество зарегистрированных в квартире'),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='number_registered_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество зарегистрированных в квартире'),
        ),
        migrations.AddField(
            model_name='waterindicators',
            name='number_registered_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество зарегистрированных в квартире'),
        ),
        migrations.CreateModel(
            name='HotWaterIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('hot_water_meter_one', models.PositiveIntegerField(null=True, verbose_name='Показания счётчика горячей воды')),
                ('hot_water_tariff_counter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду по счётчику')),
                ('hot_water_tariff_no_counter', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду без счётчика')),
                ('heating_tariff', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на воду без счётчика')),
                ('number_registered_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество зарегистрированных в квартире')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartaments.apartment', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Горячая вода',
                'verbose_name_plural': 'Горячая вода',
                'db_table': 'HotWater',
                'ordering': ('id',),
            },
        ),
    ]
