# Generated by Django 5.2 on 2025-05-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_gasindicators_number_registered_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotwaterindicators',
            old_name='heating_tariff',
            new_name='heating_tariff_counter',
        ),
        migrations.RenameField(
            model_name='hotwaterindicators',
            old_name='hot_water_tariff_no_counter',
            new_name='heating_tariff_no_counter',
        ),
        migrations.RenameField(
            model_name='hotwaterindicators',
            old_name='hot_water_meter_one',
            new_name='hot_water_meter',
        ),
        migrations.RemoveField(
            model_name='hotwaterindicators',
            name='hot_water_tariff_counter',
        ),
    ]
