# Generated by Django 5.2 on 2025-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_heating_tariff_hotwaterindicators_heating_tariff_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotwaterindicators',
            name='heating_tariff_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на нагрев воды со счётчиком'),
        ),
        migrations.AlterField(
            model_name='hotwaterindicators',
            name='heating_tariff_no_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на нагрев воды без счётчика'),
        ),
    ]
