# Generated by Django 5.2 on 2025-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_electricityindicators_electro_meter_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityindicators',
            name='el_power_apartment',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Эл.мощность квартиры'),
        ),
        migrations.AddField(
            model_name='electricityindicators',
            name='electro_tariff_no_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на электроэнергию без счётчика '),
        ),
    ]
