# Generated by Django 5.2 on 2025-06-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_electricityindicators_el_power_apartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricityindicators',
            old_name='el_power_apartment',
            new_name='electro_power_apartment',
        ),
    ]
