# Generated by Django 5.2 on 2025-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_el_power_apartment_electricityindicators_electro_power_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwaterindicators',
            name='hot_water_tariff_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на горячую воду со счётчиком'),
        ),
        migrations.AddField(
            model_name='hotwaterindicators',
            name='hot_water_tariff_no_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на горячую воду без счётчика'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_power_apartment',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Электрическая мощность квартиры'),
        ),
    ]
