# Generated by Django 5.2 on 2025-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_hotwaterindicators_hot_water_tariff_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_meter_two',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Показания электр.счётчика - 2'),
        ),
        migrations.AlterField(
            model_name='hotwaterindicators',
            name='hot_water_tariff_counter',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='тариф на горячую воду по счётчику'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_meter_one',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Показания вод.счётчика'),
        ),
    ]
