# Generated by Django 5.2 on 2025-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_electricityindicators_electro_meter_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_meter_one',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания электр.счётчика-1'),
        ),
        migrations.AlterField(
            model_name='electricityindicators',
            name='electro_meter_two',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания электр.счётчика - 2'),
        ),
        migrations.AlterField(
            model_name='gasindicators',
            name='gas_meter',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания газ.счётчика'),
        ),
        migrations.AlterField(
            model_name='hotwaterindicators',
            name='hot_water_meter',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания счётчика горячей воды'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_meter_one',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания вод.счётчика'),
        ),
        migrations.AlterField(
            model_name='waterindicators',
            name='water_meter_two',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Показания вод.счётчика #2'),
        ),
    ]
